### ISSUE TITLE
ArduinoIDE 1.8 This library cannot be used

### ISSUE THREAD

**Issue by he77PC011** [mendozaphd/ADE7878-Arduino#1]
ArduinoIDE 1.8 This library cannot be used
An error occurred adding the library

**Comment by he77PC011** [comment]
Specified folder/zip file does not contain a valid library
Invalid library found in C:\Users\he77\Documents\Arduino\libraries\ADE7878-Arduino-main: no headers files (.h) found in C:\Users\he77\Documents\Arduino\libraries\ADE7878-Arduino-main
![360截图20230204123913264](https://user-images.githubusercontent.com/87251554/216748862-acb2e5df-6137-4675-983c-da52c3935900.jpg)

**Comment by he77PC011** [comment]
C:\Users\he77\Documents\Arduino\libraries\ADE7878-Arduino\examples\ade7878\ade7878.ino: In function 'void loop()':
ade7878:95:5: error: 'energia' was not declared in this scope
     energia.valor[0] = medidor.getVRMS(1);
     ^~~~~~~
exit status 1
'energia' was not declared in this scope

**Comment by mendozaphd** [comment]
Sorry, I didn't use the Arduino iDE, I used platformIO in Visual Studio Code, I highly recommend it. Are you still having the same problem?

energia is an struct where save the values, you can change it for an float variable or add the struct, sorry, i forget it, add this code before the setup()
Thanks for your feedback

 typedef struct struct_message
 {
   float valor[30];
 } struct_message;

struct_message energia;

![image](https://user-images.githubusercontent.com/77020078/219080691-16835936-2892-4d2b-9ebe-e5899f37a6f0.png)
